"""Schema -> SQL DDL, and SQL/SQLite -> schema (reverse engineering)."""
from __future__ import annotations

import re
import sqlite3
import uuid
from pathlib import Path

DIALECTS = ("sqlite", "postgresql", "mysql")

TYPE_MAP: dict[str, dict[str, str]] = {
    "sqlite": {
        "integer": "INTEGER", "bigint": "INTEGER", "string": "VARCHAR(255)",
        "text": "TEXT", "boolean": "BOOLEAN", "float": "REAL",
        "decimal": "NUMERIC(12, 2)", "datetime": "DATETIME", "date": "DATE",
        "uuid": "VARCHAR(36)", "json": "JSON",
    },
    "postgresql": {
        "integer": "INTEGER", "bigint": "BIGINT", "string": "VARCHAR(255)",
        "text": "TEXT", "boolean": "BOOLEAN", "float": "DOUBLE PRECISION",
        "decimal": "NUMERIC(12, 2)", "datetime": "TIMESTAMP", "date": "DATE",
        "uuid": "UUID", "json": "JSONB",
    },
    "mysql": {
        "integer": "INT", "bigint": "BIGINT", "string": "VARCHAR(255)",
        "text": "TEXT", "boolean": "TINYINT(1)", "float": "DOUBLE",
        "decimal": "DECIMAL(12, 2)", "datetime": "DATETIME", "date": "DATE",
        "uuid": "CHAR(36)", "json": "JSON",
    },
}

AUTO_INCREMENT = {
    "sqlite": "",                      # INTEGER PRIMARY KEY is implicit rowid
    "postgresql": "",                  # handled by SERIAL below
    "mysql": " AUTO_INCREMENT",
}


def _quote(name: str, dialect: str) -> str:
    if dialect == "mysql":
        return f"`{name}`"
    return f'"{name}"'


def _default_sql(raw: str | None, dialect: str) -> str | None:
    if raw in (None, ""):
        return None
    low = str(raw).strip().lower()
    if low in ("now()", "current_timestamp"):
        return {"sqlite": "CURRENT_TIMESTAMP",
                "postgresql": "CURRENT_TIMESTAMP",
                "mysql": "CURRENT_TIMESTAMP"}[dialect]
    if low in ("true", "false"):
        if dialect == "mysql":
            return "1" if low == "true" else "0"
        return low.upper()
    return str(raw)


def generate_ddl(tables: list[dict], relations: list[dict], dialect: str = "sqlite") -> str:
    """Render CREATE TABLE statements in dependency order."""
    if dialect not in DIALECTS:
        raise ValueError(f"unknown dialect: {dialect}")

    types = TYPE_MAP[dialect]
    by_id = {t["id"]: t for t in tables}

    # foreign keys grouped by the child table
    fks: dict[str, list[dict]] = {}
    for rel in relations:
        parent, child = by_id.get(rel["fromTableId"]), by_id.get(rel["toTableId"])
        if not parent or not child:
            continue
        pcol = next((c for c in parent["columns"] if c["id"] == rel["fromColumnId"]), None)
        ccol = next((c for c in child["columns"] if c["id"] == rel["toColumnId"]), None)
        if not pcol or not ccol:
            continue
        fks.setdefault(child["id"], []).append({
            "column": ccol["name"], "ref_table": parent["name"],
            "ref_column": pcol["name"], "on_delete": rel.get("onDelete", "cascade").upper(),
        })

    lines: list[str] = [
        f"-- Generated by Skaffo — {dialect}",
        "",
    ]
    if dialect == "sqlite":
        lines += ["PRAGMA foreign_keys = ON;", ""]

    for t in _topo_sort(tables, relations):
        cols_sql: list[str] = []
        for c in t["columns"]:
            col_type = types.get(c["type"], "VARCHAR(255)")

            # Postgres autoincrement is a distinct type
            if (dialect == "postgresql" and c.get("primaryKey")
                    and c["type"] in ("integer", "bigint")):
                col_type = "BIGSERIAL" if c["type"] == "bigint" else "SERIAL"

            parts = [f"  {_quote(c['name'], dialect)} {col_type}"]

            if c.get("primaryKey"):
                parts.append("PRIMARY KEY")
                if dialect == "mysql" and c["type"] in ("integer", "bigint"):
                    parts.append(AUTO_INCREMENT["mysql"].strip())
                if dialect == "sqlite" and c["type"] in ("integer", "bigint"):
                    parts.append("AUTOINCREMENT")
            else:
                if not c.get("nullable"):
                    parts.append("NOT NULL")
                if c.get("unique"):
                    parts.append("UNIQUE")

            dv = _default_sql(c.get("defaultValue"), dialect)
            if dv is not None and not c.get("primaryKey"):
                parts.append(f"DEFAULT {dv}")

            cols_sql.append(" ".join(parts))

        for fk in fks.get(t["id"], []):
            cols_sql.append(
                f"  FOREIGN KEY ({_quote(fk['column'], dialect)}) "
                f"REFERENCES {_quote(fk['ref_table'], dialect)}({_quote(fk['ref_column'], dialect)}) "
                f"ON DELETE {fk['on_delete']}"
            )

        lines.append(f"CREATE TABLE {_quote(t['name'], dialect)} (")
        lines.append(",\n".join(cols_sql))
        lines.append(");")
        lines.append("")

    # indexes for FK columns (most engines don't add them automatically)
    idx: list[str] = []
    for tid, items in fks.items():
        tname = by_id[tid]["name"]
        for fk in items:
            index_name = f"ix_{tname}_{fk['column']}"
            idx.append(
                f"CREATE INDEX {_quote(index_name, dialect)} "
                f"ON {_quote(tname, dialect)} ({_quote(fk['column'], dialect)});"
            )
    if idx:
        lines.append("-- Indexes on foreign keys")
        lines += idx
        lines.append("")

    return "\n".join(lines)


def _topo_sort(tables: list[dict], relations: list[dict]) -> list[dict]:
    """Parents before children; cycles fall back to original order."""
    by_id = {t["id"]: t for t in tables}
    deps: dict[str, set[str]] = {t["id"]: set() for t in tables}
    for rel in relations:
        f, t = rel["fromTableId"], rel["toTableId"]
        if f in deps and t in deps and f != t:
            deps[t].add(f)

    out: list[dict] = []
    done: set[str] = set()
    while len(out) < len(tables):
        ready = [tid for tid in deps if tid not in done and deps[tid] <= done]
        if not ready:                       # cycle — emit the rest as-is
            out += [by_id[tid] for tid in deps if tid not in done]
            break
        for tid in sorted(ready, key=lambda x: by_id[x]["name"]):
            out.append(by_id[tid])
            done.add(tid)
    return out


# ── reverse engineering ──────────────────────────────────
SQL_TO_TYPE = [
    (r"^(big)?serial", "integer"), (r"^bigint", "bigint"),
    (r"^(int|integer|smallint|tinyint|mediumint)", "integer"),
    (r"^(bool|boolean)", "boolean"),
    (r"^(varchar|char|nvarchar|character varying)", "string"),
    (r"^(text|clob|longtext|mediumtext)", "text"),
    (r"^(decimal|numeric|money)", "decimal"),
    (r"^(float|double|real)", "float"),
    (r"^(timestamp|datetime)", "datetime"),
    (r"^date$", "date"), (r"^uuid", "uuid"), (r"^(json|jsonb)", "json"),
]

PALETTE = ["#6366F1", "#10B981", "#7C3AED", "#F59E0B", "#EF4444", "#06B6D4"]


def _map_sql_type(raw: str) -> str:
    low = (raw or "").strip().lower()
    for pattern, mapped in SQL_TO_TYPE:
        if re.match(pattern, low):
            return mapped
    return "string"


def _uid() -> str:
    return uuid.uuid4().hex[:12]


def introspect_sqlite(db_path: str | Path) -> dict:
    """Read a real SQLite file into Skaffo's schema shape."""
    path = Path(db_path).expanduser()
    if not path.exists():
        raise FileNotFoundError(f"{path} does not exist")

    con = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
    con.row_factory = sqlite3.Row
    try:
        names = [
            r["name"] for r in con.execute(
                "SELECT name FROM sqlite_master "
                "WHERE type='table' AND name NOT LIKE 'sqlite_%' "
                "AND name <> 'alembic_version' ORDER BY name"
            )
        ]

        tables: list[dict] = []
        col_ids: dict[tuple[str, str], str] = {}
        tbl_ids: dict[str, str] = {}

        for i, tname in enumerate(names):
            tid = f"tbl_{_uid()}"
            tbl_ids[tname] = tid

            uniques: set[str] = set()
            for idx in con.execute(f'PRAGMA index_list("{tname}")'):
                if idx["unique"]:
                    cols = list(con.execute(f'PRAGMA index_info("{idx["name"]}")'))
                    if len(cols) == 1:
                        uniques.add(cols[0]["name"])

            columns = []
            for c in con.execute(f'PRAGMA table_info("{tname}")'):
                cid = _uid()
                col_ids[(tname, c["name"])] = cid
                columns.append({
                    "id": cid,
                    "name": c["name"],
                    "type": _map_sql_type(c["type"]),
                    "primaryKey": bool(c["pk"]),
                    "nullable": not c["notnull"] and not c["pk"],
                    "unique": c["name"] in uniques or bool(c["pk"]),
                    "defaultValue": c["dflt_value"],
                })

            tables.append({
                "id": tid, "name": tname,
                "color": PALETTE[i % len(PALETTE)],
                "position": {"x": 80 + (i % 3) * 380, "y": 80 + (i // 3) * 320},
                "columns": columns,
            })

        relations = []
        for tname in names:
            for fk in con.execute(f'PRAGMA foreign_key_list("{tname}")'):
                parent, child_col = fk["table"], fk["from"]
                parent_col = fk["to"]
                if parent not in tbl_ids:
                    continue
                if parent_col is None:      # implicit reference to the PK
                    pk = next(
                        (c for c in con.execute(f'PRAGMA table_info("{parent}")') if c["pk"]),
                        None,
                    )
                    parent_col = pk["name"] if pk else "id"
                fid = col_ids.get((parent, parent_col))
                cid = col_ids.get((tname, child_col))
                if not fid or not cid:
                    continue
                relations.append({
                    "id": _uid(), "kind": "one-to-many",
                    "fromTableId": tbl_ids[parent], "fromColumnId": fid,
                    "toTableId": tbl_ids[tname], "toColumnId": cid,
                    "onDelete": (fk["on_delete"] or "cascade").lower().replace(" ", " "),
                })

        return {"tables": tables, "relations": relations}
    finally:
        con.close()


CREATE_RE = re.compile(
    r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?[`\"\[]?(\w+)[`\"\]]?\s*\((.*?)\)\s*;",
    re.IGNORECASE | re.DOTALL,
)
FK_INLINE_RE = re.compile(
    r"FOREIGN\s+KEY\s*\(\s*[`\"\[]?(\w+)[`\"\]]?\s*\)\s*REFERENCES\s+"
    r"[`\"\[]?(\w+)[`\"\]]?\s*\(\s*[`\"\[]?(\w+)[`\"\]]?\s*\)"
    r"(?:\s*ON\s+DELETE\s+(CASCADE|RESTRICT|SET\s+NULL|NO\s+ACTION))?",
    re.IGNORECASE,
)


def parse_sql(sql: str) -> dict:
    """Best-effort CREATE TABLE parser for pasted SQL dumps."""
    tables: list[dict] = []
    tbl_ids: dict[str, str] = {}
    col_ids: dict[tuple[str, str], str] = {}
    pending_fks: list[tuple[str, str, str, str, str]] = []

    for i, (tname, body) in enumerate(CREATE_RE.findall(sql)):
        tid = f"tbl_{_uid()}"
        tbl_ids[tname] = tid
        columns = []

        for raw_line in _split_columns(body):
            line = raw_line.strip()
            if not line:
                continue

            fk = FK_INLINE_RE.search(line)
            if fk:
                pending_fks.append((
                    tname, fk.group(1), fk.group(2), fk.group(3),
                    (fk.group(4) or "cascade").lower(),
                ))
                continue

            if re.match(r"^(PRIMARY|UNIQUE|CONSTRAINT|KEY|INDEX|CHECK)\b", line, re.I):
                continue

            m = re.match(r"^[`\"\[]?(\w+)[`\"\]]?\s+([A-Za-z ]+(?:\([\d,\s]+\))?)", line)
            if not m:
                continue

            cname, ctype = m.group(1), m.group(2)
            upper = line.upper()
            cid = _uid()
            col_ids[(tname, cname)] = cid

            default = None
            dm = re.search(r"DEFAULT\s+('[^']*'|[\w()]+)", line, re.I)
            if dm:
                default = dm.group(1)

            is_pk = "PRIMARY KEY" in upper
            columns.append({
                "id": cid, "name": cname, "type": _map_sql_type(ctype),
                "primaryKey": is_pk,
                "nullable": "NOT NULL" not in upper and not is_pk,
                "unique": "UNIQUE" in upper or is_pk,
                "defaultValue": default,
            })

        tables.append({
            "id": tid, "name": tname,
            "color": PALETTE[i % len(PALETTE)],
            "position": {"x": 80 + (i % 3) * 380, "y": 80 + (i // 3) * 320},
            "columns": columns,
        })

    # table-level PRIMARY KEY(x)
    for tname, body in CREATE_RE.findall(sql):
        pk = re.search(r"PRIMARY\s+KEY\s*\(\s*[`\"\[]?(\w+)[`\"\]]?\s*\)", body, re.I)
        if not pk:
            continue
        t = next((x for x in tables if x["name"] == tname), None)
        if not t:
            continue
        for c in t["columns"]:
            if c["name"].lower() == pk.group(1).lower():
                c["primaryKey"] = True
                c["nullable"] = False
                c["unique"] = True

    relations = []
    for child, ccol, parent, pcol, on_delete in pending_fks:
        if parent not in tbl_ids:
            continue
        fid, cid = col_ids.get((parent, pcol)), col_ids.get((child, ccol))
        if not fid or not cid:
            continue
        relations.append({
            "id": _uid(), "kind": "one-to-many",
            "fromTableId": tbl_ids[parent], "fromColumnId": fid,
            "toTableId": tbl_ids[child], "toColumnId": cid,
            "onDelete": on_delete.replace("no action", "restrict"),
        })

    return {"tables": tables, "relations": relations}


def _split_columns(body: str) -> list[str]:
    """Split on commas that are not inside parentheses."""
    out, depth, cur = [], 0, []
    for ch in body:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            out.append("".join(cur))
            cur = []
        else:
            cur.append(ch)
    if cur:
        out.append("".join(cur))
    return out
